abstract class Card {
  id: string;
  name: string;
  type: string;
  autoGeneratedId: string | null;

  constructor(id: string, name: string, type: string) {
    this.id = id;
    this.name = name;
    this.type = type;
    this.autoGeneratedId = null;
  }
}

export default Card;
