const EstadosDeLaPartida = {
    GAME_CREATED: 0,
    GAME_STARTED: 1,
    ROUND_STARTED: 2,
    DETERMINAR_TURNOS: 3,
    DRAW_PHASE: 'DRAW_PHASE',
    COMPILATION_PHASE: 'COMPILATION_PHASE',
    SUMMON_PHASE: 'SUMMON_PHASE',
    UPGRADE_PHASE: 'UPGRADE_PHASE',
    BATTLE_PHASE: 'BATTLE_PHASE',
    FINISHED_ROUND: 'FINISHED_ROUND',
    FINISHED_GAME: 'FINISHED_GAME',
}

module.exports = EstadosDeLaPartida