const EstadosDeLaPartida = {
    GAME_CREATED: 'GAME_CREATED',
    GAME_STARTED: 'GAME_STARTED',
    ROUND_STARTED: 'ROUND_STARTED',
    DETERMINAR_TURNOS: 'DETERMINAR_TURNOS',
    DRAW_PHASE: 'DRAW_PHASE',
    COMPILATION_PHASE: 'COMPILATION_PHASE',
    SUMMON_PHASE: 'SUMMON_PHASE',
    UPGRADE_PHASE: 'UPGRADE_PHASE',
    BATTLE_PHASE: 'BATTLE_PHASE',
    FINISHED_ROUND: 'FINISHED_ROUND',
    FINISHED_GAME: 'FINISHED_GAME',
}

module.exports = EstadosDeLaPartida