const PLAYER_ACTIONS = {
    FINISH_COMPILATION_PHASE: 'FINISH_COMPILATION_PHASE',
    SUMMON_DIGIMONS: 'SUMMON_DIGIMONS',
    ACTIVATE_ENERGY_CARD: 'ACTIVATE_ENERGY_CARD',
    ACTIVATE_PROGRAMM_CARD: 'ACTIVATE_PROGRAMM_CARD'
}

module.exports = PLAYER_ACTIONS 